export const CATEGORY_SEEDS = [
  { name: "Account and Access", isActive: true },
  { name: "Hardware", isActive: true },
  { name: "Software", isActive: true },
  { name: "Network", isActive: true },
] as const;

export const RELATED_SYSTEM_SEEDS = [
  { name: "Email", isActive: true },
  { name: "Campus Wi-Fi", isActive: true },
  { name: "VPN", isActive: true },
  { name: "LEB2 App", isActive: true },
  { name: "Grade Submission App", isActive: true },
  { name: "Printer", isActive: true },
  { name: "Corporate Laptop", isActive: true },
] as const;

export const USER_SEEDS = [
  { email: "anan@example.test", displayName: "Anan Chai", role: "REQUESTER", isActive: true },
  { email: "mali@example.test", displayName: "Mali Srisuk", role: "REQUESTER", isActive: true },
  { email: "niran@example.test", displayName: "Niran Boonmee", role: "REQUESTER", isActive: true },
  { email: "pim@example.test", displayName: "Pimchanok Dee", role: "REQUESTER", isActive: true },
  { email: "somchai.inactive@example.test", displayName: "Somchai Kittipong", role: "REQUESTER", isActive: false },
  { email: "narin.staff@example.test", displayName: "Narin Support", role: "IT_STAFF", isActive: true },
  { email: "kanda.staff@example.test", displayName: "Kanda Service", role: "IT_STAFF", isActive: true },
  { email: "thep.staff@example.test", displayName: "Thep Technician", role: "IT_STAFF", isActive: true },
  { email: "wichai.inactive.staff@example.test", displayName: "Wichai Support", role: "IT_STAFF", isActive: false },
  { email: "araya.admin@example.test", displayName: "Araya Admin", role: "ADMINISTRATOR", isActive: true },
] as const;

export const REQUESTER_SEEDS = USER_SEEDS.filter((entry) => entry.role === "REQUESTER");

export const TICKET_SEEDS = [
  {
    id: "31000000-0000-4000-8000-000000000001",
    ticketNumber: "TKT-20261004-310001",
    submittedByEmail: "anan@example.test",
    categoryName: "Account and Access",
    relatedSystemName: "Email",
    summary: "Cannot access the shared mailbox",
    description: "The shared mailbox returns an access denied message after sign-in.",
    requestedPriority: "HIGH",
    itPriority: "HIGH",
    currentStatus: "NEW",
    ownerEmail: null,
  },
  {
    id: "31000000-0000-4000-8000-000000000002",
    ticketNumber: "TKT-20261004-310002",
    submittedByEmail: "mali@example.test",
    categoryName: "Network",
    relatedSystemName: "Campus Wi-Fi",
    summary: "Wi-Fi disconnects during online classes",
    description: "The connection drops several times during longer video sessions.",
    requestedPriority: "MEDIUM",
    itPriority: "HIGH",
    currentStatus: "OPEN",
    ownerEmail: "narin.staff@example.test",
  },
  {
    id: "31000000-0000-4000-8000-000000000003",
    ticketNumber: "TKT-20261004-310003",
    submittedByEmail: "niran@example.test",
    categoryName: "Hardware",
    relatedSystemName: "Corporate Laptop",
    summary: "Laptop battery drains too quickly",
    description: "The battery falls below twenty percent after about one hour of normal use.",
    requestedPriority: "LOW",
    itPriority: "LOW",
    currentStatus: "IN_PROGRESS",
    ownerEmail: "kanda.staff@example.test",
  },
  {
    id: "31000000-0000-4000-8000-000000000004",
    ticketNumber: "TKT-20261004-310004",
    submittedByEmail: "pim@example.test",
    categoryName: "Software",
    relatedSystemName: "LEB2 App",
    summary: "Course page remains on the loading screen",
    description: "The course page does not finish loading after a successful sign-in.",
    requestedPriority: "MEDIUM",
    itPriority: "MEDIUM",
    currentStatus: "WAITING_FOR_REQUESTER",
    ownerEmail: "thep.staff@example.test",
  },
  {
    id: "31000000-0000-4000-8000-000000000005",
    ticketNumber: "TKT-20261004-310005",
    submittedByEmail: "anan@example.test",
    categoryName: "Network",
    relatedSystemName: "VPN",
    summary: "VPN connection is restored",
    description: "The VPN connection now works after the client configuration was refreshed.",
    requestedPriority: "HIGH",
    itPriority: "MEDIUM",
    currentStatus: "RESOLVED",
    ownerEmail: "narin.staff@example.test",
  },
  {
    id: "31000000-0000-4000-8000-000000000006",
    ticketNumber: "TKT-20261004-310006",
    submittedByEmail: "mali@example.test",
    categoryName: "Hardware",
    relatedSystemName: "Printer",
    summary: "Printer queue issue completed",
    description: "The stuck print queue was cleared and a test page completed successfully.",
    requestedPriority: "LOW",
    itPriority: "LOW",
    currentStatus: "CLOSED",
    ownerEmail: "kanda.staff@example.test",
  },
  {
    id: "31000000-0000-4000-8000-000000000007",
    ticketNumber: "TKT-20261004-310007",
    submittedByEmail: "niran@example.test",
    categoryName: "Software",
    relatedSystemName: "Grade Submission App",
    summary: "Submission validation issue returned",
    description: "The validation warning returned after the application was updated this morning.",
    requestedPriority: "HIGH",
    itPriority: "HIGH",
    currentStatus: "REOPENED",
    ownerEmail: "thep.staff@example.test",
  },
  {
    id: "31000000-0000-4000-8000-000000000008",
    ticketNumber: "TKT-20261004-310008",
    submittedByEmail: "pim@example.test",
    categoryName: "Account and Access",
    relatedSystemName: "Email",
    summary: "Duplicate mailbox request cancelled",
    description: "This request duplicated an earlier Ticket and no further work is needed.",
    requestedPriority: "LOW",
    itPriority: "LOW",
    currentStatus: "CANCELLED",
    ownerEmail: null,
  },
] as const;

export const PUBLIC_COMMENT_SEEDS = [
  {
    id: "31c00000-0000-4000-8000-000000000001",
    ticketNumber: "TKT-20261004-310002",
    authorEmail: "mali@example.test",
    content: "The disconnection happens in two different classrooms.",
  },
  {
    id: "31c00000-0000-4000-8000-000000000002",
    ticketNumber: "TKT-20261004-310002",
    authorEmail: "narin.staff@example.test",
    content: "Thanks, we are checking the access points serving those rooms.",
  },
  {
    id: "31c00000-0000-4000-8000-000000000003",
    ticketNumber: "TKT-20261004-310004",
    authorEmail: "thep.staff@example.test",
    content: "Please retry after clearing the browser cache and share the result.",
  },
] as const;

export const INTERNAL_NOTE_SEEDS = [
  {
    id: "31d00000-0000-4000-8000-000000000001",
    ticketNumber: "TKT-20261004-310002",
    authorEmail: "narin.staff@example.test",
    content: "Compare the affected rooms against the latest access-point health report.",
  },
  {
    id: "31d00000-0000-4000-8000-000000000002",
    ticketNumber: "TKT-20261004-310003",
    authorEmail: "kanda.staff@example.test",
    content: "Battery diagnostics show reduced capacity; arrange a hardware inspection.",
  },
] as const;
